language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy nghiahv1/udagram-reverseproxy:latest

after_success:
  - echo "Hvn@0986015284" | docker login -u "jossnghia@gmail.com" --password-stdin
  - docker push nghiahv1/udagram-reverseproxy:latest