apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: ubackend-user-deployment
        image: nghiahv1/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom: # using envFrom instead of env
        - secretRef: # use secretRef instead of env configMapRef
            name: mysecret # name of the Secret
        - configMapRef: # referencing the ConfigMap
            name: config-secret # name of the ConfigMap
          #prefix: POSTGRES_  All environment variables will be prefixed with POSTGRES_