apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: udagram-reverseproxy-deployment
        image: nghiahv1/udagram-reverseproxy:v1
        ports:
        - containerPort: 80