apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-deployment
  labels:
    run: udagram-frontend-deployment
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    run: udagram-frontend-deployment