apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-deployment
  labels:
    run: udagram-reverseproxy-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: udagram-reverseproxy-deployment