apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-deployment
  labels:
    run: udagram-api-feed-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: udagram-api-feed-deployment