apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed-deployment
        image: nghiahv1/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom: # using envFrom instead of env
          - secretRef: # use secretRef instead of env configMapRef
              name: mysecret # name of the Secret
          - configMapRef: # referencing the ConfigMap
              name: config-secret # name of the ConfigMap
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret