apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed-deployment
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed-deployment
        image: nghiahv1/udagram-api-feed:v1
        ports:
        - containerPort: 8080