apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-svc
spec:
  ports:
  # port bên ngoài của pods mà các pods có thể giao tiếp được với nhau
  - port: 80
  # port target với 8080 của deployment
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx-deployment
  type: LoadBalancer