apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: udagram-api-user-deployment
        image: nghiahv1/udagram-api-user:v1
        ports:
        - containerPort: 8080